[project]
name = "aivk"
version = "0.1.0"
description = "AI viture kernel"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "mcp>=1.6.0",
    "openai-agents>=0.0.7",
]
