version = "0.3.2.21"
github = "https://github.com/LIghtJUNction/AIVK"
AIVK_ROOT = "c:\\Users\\light\\Documents\\GitHub\\AIVK\\aivk_root"
created_at = "2025-04-16T02:35:45.119897"
updated_at = "2025-04-16T02:35:45.119897"
init_force = true
